---
# tasks file for hswong3i.gluster_volume_volume

- name: create a thin pool from from VG
  lvol:
    vg: "gluster-volumes"
    lv: "pool-{{ item.name }}"
    size: "{{ item.size }}"
    opts: "--type thin --zero n --chunksize 1280K --poolmetadatasize 16G"
  with_items: "{{ gluster_volume }}"
  tags: hswong3i.gluster_volume

- name: create LV from the thin pool
  lvol:
    vg: "gluster-volumes"
    lv: "volume-{{ item.name }}"
    opts: "-V {{ item.size }} -T gluster-volumes/pool-{{ item.name }}"
  with_items: "{{ gluster_volume }}"
  tags: hswong3i.gluster_volume

- name: format LV with xfs
  filesystem:
    dev: "/dev/gluster-volumes/volume-{{ item.name }}"
    fstype: "xfs"
    opts: "-i size=512 -n size=8192 -d su=128k,sw=10"
  with_items: "{{ gluster_volume }}"
  tags: hswong3i.gluster_volume

- name: mount LV as brick
  mount:
    name: "/srv/gluster/{{ item.name }}"
    src: "/dev/gluster-volumes/volume-{{ item.name }}"
    fstype: "xfs"
    opts: "defaults,inode64,noatime,nouuid"
    state: "mounted"
  with_items: "{{ gluster_volume }}"
  tags: hswong3i.gluster_volume

- name: create brick folder
  file:
    dest: "/srv/gluster/{{ item.name }}/brick"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  with_items: "{{ gluster_volume }}"
  tags: hswong3i.gluster_volume

- name: gluster volume create
  gluster_volume:
    name: "{{ item.name }}"
    bricks: "/srv/gluster/{{ item.name }}/brick"
    host: "{{ inventory_hostname }}"
    cluster: "{{ play_hosts | join(',') }}"
    replicas: "{{ item.replicas | default(None) or omit }}"
    stripes: "{{ item.stripes | default(None) or omit }}"
    disperses: "{{ item.disperses | default(None) or omit }}"
    redundancies: "{{ item.redundancies | default(None) or omit }}"
    start_on_create: "no"
    state: "present"
  with_items: "{{ gluster_volume }}"
  when: play_hosts | length > 1
  run_once: yes
  tags: hswong3i.gluster_volume

- name: gluster volume set
  gluster_volume:
    name: "{{ item.name }}"
    bricks: "/srv/gluster/{{ item.name }}/brick"
    host: "{{ inventory_hostname }}"
    cluster: "{{ play_hosts | join(',') }}"
    options: "{{ item.options | default(None) or omit }}"
    state: "present"
  with_items: "{{ gluster_volume }}"
  when: play_hosts | length > 1
  run_once: yes
  tags: hswong3i.gluster_volume

- name: gluster volume start
  gluster_volume:
    name: "{{ item.name }}"
    state: "started"
  with_items: "{{ gluster_volume }}"
  when: play_hosts | length > 1
  run_once: yes
  tags: hswong3i.gluster_volume

- name: mount -t glusterfs
  mount:
    src: "localhost:{{ item.name }}"
    name: "/mnt/gluster/{{ item.name }}"
    fstype: "glusterfs"
    opts: "defaults,_netdev"
    state: "mounted"
  with_items: "{{ gluster_volume }}"
  when: play_hosts | length > 1
  tags: hswong3i.gluster_volume
